export const CATEGORIES = [
  "Development",
  "Business",
  "Design",
  "Marketing",
  "Photography",
  "Music",
  "Health & Fitness",
  "Teaching & Academics",
  "Personal Development",
  "Technology",
] as const;

export const SUBCATEGORIES: Record<string, string[]> = {
  Development: [
    "Web Development",
    "Mobile Development",
    "Data Science",
    "Machine Learning",
    "Software Engineering",
    "Game Development",
  ],
  Business: [
    "Entrepreneurship",
    "Management",
    "Finance",
    "Marketing Strategy",
    "Sales",
    "Operations",
  ],
  Design: [
    "Graphic Design",
    "UX/UI Design",
    "Web Design",
    "Interior Design",
    "Fashion Design",
    "3D Design",
  ],
  Marketing: [
    "Digital Marketing",
    "Social Media",
    "Content Marketing",
    "SEO",
    "Email Marketing",
    "Advertising",
  ],
  Photography: [
    "Portrait Photography",
    "Landscape Photography",
    "Wedding Photography",
    "Street Photography",
    "Commercial Photography",
  ],
  Music: [
    "Music Production",
    "Singing",
    "Guitar",
    "Piano",
    "Music Theory",
    "Audio Engineering",
  ],
  "Health & Fitness": [
    "Yoga",
    "Fitness Training",
    "Nutrition",
    "Mental Health",
    "Meditation",
    "Sports",
  ],
  "Teaching & Academics": [
    "Language Learning",
    "Math",
    "Science",
    "History",
    "Literature",
    "Test Prep",
  ],
  "Personal Development": [
    "Leadership",
    "Productivity",
    "Communication",
    "Time Management",
    "Motivation",
    "Life Coaching",
  ],
  Technology: [
    "Cloud Computing",
    "Cybersecurity",
    "DevOps",
    "AI/ML",
    "Blockchain",
    "IoT",
  ],
} as const;
